# Generated by Django 3.1.2 on 2020-10-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(unique=True)),
                ('lang', models.CharField(blank=True, choices=[("🇺🇿 O'zbekcha", "🇺🇿 O'zbekcha"), ('🇷🇺 Русский', '🇷🇺 Русский')], max_length=20, null=True)),
                ('step', models.CharField(default='DEFAULT', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
