# Generated by Django 3.1.2 on 2020-10-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_auto_20201026_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='date',
        ),
    ]
